import { Duration, RemovalPolicy, Stack, StackProps, Validations } from 'aws-cdk-lib';
import { AttributeType, BillingMode, Table, TableEncryption } from 'aws-cdk-lib/aws-dynamodb';
import { Rule, Schedule } from 'aws-cdk-lib/aws-events';
import { SfnStateMachine } from 'aws-cdk-lib/aws-events-targets';
import {
  DefinitionBody,
  JsonPath,
  LogLevel,
  StateMachine,
  StateMachineType,
} from 'aws-cdk-lib/aws-stepfunctions';
import { DynamoAttributeValue, DynamoPutItem } from 'aws-cdk-lib/aws-stepfunctions-tasks';
import { LogGroup, RetentionDays } from 'aws-cdk-lib/aws-logs';
import { Construct } from 'constructs';

export class AccessReviewStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    // --- DynamoDB: review records (ephemeral) ---
    const table = new Table(this, 'ReviewTable', {
      partitionKey: { name: 'reviewId', type: AttributeType.STRING },
      sortKey: { name: 'entitlementId', type: AttributeType.STRING },
      billingMode: BillingMode.PAY_PER_REQUEST,
      encryption: TableEncryption.AWS_MANAGED,
      pointInTimeRecoverySpecification: { pointInTimeRecoveryEnabled: true },
      removalPolicy: RemovalPolicy.DESTROY,
    });

    // --- Step Functions: write one review record ---
    // Values come from the execution input via JSONPath. `fromString('$.x')`
    // would store the LITERAL "$.x"; wrap in JsonPath.stringAt() to resolve it.
    const recordReview = new DynamoPutItem(this, 'RecordReview', {
      table,
      item: {
        reviewId: DynamoAttributeValue.fromString(JsonPath.stringAt('$.reviewId')),
        entitlementId: DynamoAttributeValue.fromString(JsonPath.stringAt('$.entitlementId')),
        status: DynamoAttributeValue.fromString('pending'),
      },
    });

    const logGroup = new LogGroup(this, 'ReviewSfnLogs', {
      retention: RetentionDays.ONE_WEEK,
      removalPolicy: RemovalPolicy.DESTROY,
    });

    const stateMachine = new StateMachine(this, 'AccessReviewStateMachine', {
      definitionBody: DefinitionBody.fromChainable(recordReview),
      stateMachineType: StateMachineType.STANDARD,
      timeout: Duration.minutes(5),
      tracingEnabled: true,
      logs: { destination: logGroup, level: LogLevel.ALL, includeExecutionData: true },
    });

    // --- EventBridge: schedule the review campaign ---
    new Rule(this, 'AccessReviewSchedule', {
      schedule: Schedule.rate(Duration.days(30)),
      targets: [new SfnStateMachine(stateMachine)],
    });

    // --- cdk-nag v3 acknowledgements (with reasons) ---
    // v3 has NO bulk suppression: each finding must be acknowledged by its exact
    // `RuleId[FindingId]` id (prefix matching on a bare rule id is unsupported).
    // The L2-generated Step Functions execution role emits a Resource:* IAM5
    // finding scoped to sub-resources of this table only. The exact FindingId
    // string must match the synth/`cdk synth` error output; if it differs, copy
    // the bracketed id verbatim from the error and update this line.
    Validations.of(stateMachine).acknowledge({
      id: 'AwsSolutions-IAM5[Resource::*]',
      reason:
        'Step Functions execution role is generated by the L2 construct and scoped to the single review table and its own log group; the wildcard is on sub-resources of those ARNs only.',
    });
    // Note: AwsSolutions-DDB3 (point-in-time recovery) does NOT fire here because
    // PITR is enabled on the table above, so no acknowledgement is needed.
  }
}
